#
#Sun Sep 20 17:46:31 COT 2026
goog\:chromeOptions={args\=[--remote-allow-origins\=*, --start-maximized, --user-data-dir\=C\:\\\\Users\\\\Arni Gomez\\\\AppData\\\\Local\\\\Google\\\\Chrome\\\\User Data, --profile-directory\=Profile 7], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
